### ISSUE TITLE
hello, just a question.

### ISSUE THREAD

**Issue by LeoBdt** [AlexPads/ShopUI-FormAPI-Working#10]
Are you trying your plugin before uploading them and saying the bugs have been fixed?

There's still the same error. I'm not here to blame your work but please, try your plugin before......

**Comment by AlexPads** [comment]
it is Fixed and Yes i am trying it You just SUCK at telling me what the
error is an how to recreate the problem

**Comment by AlexPads** [comment]
what version are u using?

**Comment by AlexPads** [comment]
ALSO i completely rerote and re formatted the code and Fixed all the issue snad made it lok batter and be more intuitive so

**Comment by LeoBdt** [comment]
Bro i'm using the last version.

To recreate the error : 

1: do /shop
2: click on any button (blocks for exemple)
3: it just says in tchat "thanks for using ShopUI" ....

**Comment by captainleviftw** [comment]
@LeoBdt does it exactly say 

> "thanks for using ShopUI"

 in 'tchat'?

**Comment by LeoBdt** [comment]
in chat, where u send msg.

**Comment by captainleviftw** [comment]
Let me ask again, @LeoBdt does it exactly say

"thanks for using ShopUI" in chat?

**Comment by LeoBdt** [comment]
YES

**Comment by captainleviftw** [comment]
Could you show me what's inside your `config.yml`? @LeoBdt

**Comment by LeoBdt** [comment]
it's the original file, i haven't modified it

**Comment by captainleviftw** [comment]
There's no such message as 

> "thanks for using ShopUI" 
in https://github.com/AlexPads/ShopUI-FormAPI-Working/blob/master/resources/config.yml

**Comment by LeoBdt** [comment]
Okay sorry it's "thank you for shoping at ShopUI

**Comment by captainleviftw** [comment]
that message is only called in `https://github.com/AlexPads/ShopUI-FormAPI-Working/blob/71f4742779aecc83aebc6b0580e11cb7ede52373/src/AlexPads/ShopUI/SaltyPixelDevz/Shop.php#L80` when you fail to select category I assume

**Comment by AlexPads** [comment]
@LeoBdt You are using version 3.2.0? not 3.0.0 or 3.1.3 or 3.0.5 or any of those you are using the Latest for sure and you are Using the Phar from Poggit not the source because it uses a Viron so the code itself is useless.  and by what it does i mean like record a video ir send multiple screen shots or something show me Your files redo the plugin Uninstall it and re download it and install it again because no-one else it having these errors!

@captainleviftw Thank you for Trying to get the Issue out of him 👍

**Comment by AlexPads** [comment]
@captainleviftw Are you a developer to? or just someone here to help 💯

**Comment by LeoBdt** [comment]
yes i'm using 3.2.0

**Comment by LeoBdt** [comment]
duuuuuuuuuude it's finally working ! i just unistall "slapperplus" plugin, and btw your plugin is so clean

**Comment by captainleviftw** [comment]
I guess I'm both @AlexPads

**Comment by AlexPads** [comment]
Yeah @LeoBdt Slapper plus is not recommended because it breaks other plugins that also use Form API i didn't ask what plugins you have bc most people don't have Slapper Plus or other plugins that break the UI system 

also @captainleviftw are you a dev and would you like to help me with plugins? 👍 💯

**Comment by AlexPads** [comment]
Thankyou this has now been solved for the final time and all things work correctly in 3.2.1 Thanks!
